version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    env_file: 
      - .env
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=${DATABASE_URL} # use the DATABASE_URL from .env
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: MuHsvEBxjtYwEGYjlyKMHCdwNnNCRGMo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
